[package]
name = "vulcan-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vulcan-server = { path = "../server" }
vulcan-core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
